image: gumjoe/wacc-ci-scala:slim

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - echo "Cleaning Scala..."
    - scala clean .
    - echo "Clean complete!"
  script:
    - echo "Compiling program..."
    - scala compile .
    - echo "Compilation complete!"

parser_test:
  stage: test
  script:
    - echo "Running tests..."
    - scala test .
    - echo "Testing complete!"
