include:
  - local: '.gitlab-ci-config.yml'

image: gumjoe/wacc-ci-scala:slim

variables:
  - template: .gitlab-ci-config.yml

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - echo "Cleaning Scala..."
    - scala clean .
    - echo "Clean complete!"
  script:
    - echo "Compiling program..."
    - scala compile .
    - echo "Compilation complete!"

.test_job_template:
  stage: test
  script:
    - scala test . -- -z "${TEST_NAME}"
  rules:
    - if: '$RUN_TEST == "true"'

parser_syntax_basic:
  extends: .test_job_template
  variables:
    TEST_NAME: "basic"
    RUN_TEST: "$RUN_SYNTAX_BASIC"

parser_syntax_array:
  extends: .test_job_template
  variables:
    TEST_NAME: "array"
    RUN_TEST: "$RUN_SYNTAX_ARRAY"

parser_syntax_expressions:
  extends: .test_job_template
  variables:
    TEST_NAME: "expressions"
    RUN_TEST: "$RUN_SYNTAX_EXPRESSIONS"

parser_syntax_function:
  extends: .test_job_template
  variables:
    TEST_NAME: "function"
    RUN_TEST: "$RUN_SYNTAX_FUNCTION"

parser_syntax_if:
  extends: .test_job_template
  variables:
    TEST_NAME: "if"
    RUN_TEST: "$RUN_SYNTAX_IF"

parser_syntax_io:
  extends: .test_job_template
  variables:
    TEST_NAME: "io"
    RUN_TEST: "$RUN_SYNTAX_IO"

parser_syntax_pairs:
  extends: .test_job_template
  variables:
    TEST_NAME: "pairs"
    RUN_TEST: "$RUN_SYNTAX_PAIRS"

parser_syntax_runtime:
  extends: .test_job_template
  variables:
    TEST_NAME: "runtime"
    RUN_TEST: "$RUN_SYNTAX_RUNTIME"

parser_syntax_scope:
  extends: .test_job_template
  variables:
    TEST_NAME: "scope"
    RUN_TEST: "$RUN_SYNTAX_SCOPE"

parser_syntax_sequence:
  extends: .test_job_template
  variables:
    TEST_NAME: "sequence"
    RUN_TEST: "$RUN_SYNTAX_SEQUENCE"

parser_syntax_variables:
  extends: .test_job_template
  variables:
    TEST_NAME: "variables"
    RUN_TEST: "$RUN_SYNTAX_VARIABLES"

parser_syntax_while:
  extends: .test_job_template
  variables:
    TEST_NAME: "while"
    RUN_TEST: "$RUN_SYNTAX_WHILE"
