image: gumjoe/wacc-ci-scala:slim

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - echo "Cleaning Scala..."
    - scala clean .
    - echo "Clean complete!"
  script:
    - echo "Compiling program..."
    - scala compile .
    - echo "Compilation complete!"

parser_test_basic:
  stage: test
  script:
    - scala test . -- -z "basic"

parser_test_array:
  stage: test
  script:
    - scala test . -- -z "array"

parser_test_expressions:
  stage: test
  script:
    - scala test . -- -z "expressions"

parser_test_function:
  stage: test
  script:
    - scala test . -- -z "function"

parser_test_if:
  stage: test
  script:
    - scala test . -- -z "if"

parser_test_io:
  stage: test
  script:
    - scala test . -- -z "io"

parser_test_pairs:
  stage: test
  script:
    - scala test . -- -z "pairs"

parser_test_runtime:
  stage: test
  script:
    - scala test . -- -z "runtime"

parser_test_scope:
  stage: test
  script:
    - scala test . -- -z "scope"

parser_test_sequence:
  stage: test
  script:
    - scala test . -- -z "sequence"

parser_test_variables:
  stage: test
  script:
    - scala test . -- -z "variables"

parser_test_while:
  stage: test
  script:
    - scala test . -- -z "while"
