image: gumjoe/wacc-ci-scala:slim

stages:
  - compile

compile:
  stage: compile
  before_script:
    - echo "Cleaning Scala..."
    - scala clean .
    - echo "Clean complete!"
  script:
    - echo "Compiling program..."
    - scala compile .
    - echo "Compilation complete!"
